---
- hosts: media
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/raspbian/gpg
        state: present

    - name: add docker repository to apt
      apt_repository:
        repo: deb [arch=armhf] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable
        filename: docker
        state: present
        update_cache: yes

    - name: install docker
      apt:
        name: docker
        state: latest
        update_cache: yes

    - name: make sure docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: add docker group
      group:
        name: docker
        state: present

    - name: add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups:
          - docker
        append: yes

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted

