---
- hosts: media
  become: yes

  roles:
    - role: init
      tags:
        - init

    - role: geekworm
      tags:
        - init

    - role: docker
      tags:
        - docker

    - role: jellyfin
      tags:
        - jellyfin
