---
- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable
    filename: docker
    state: present
    update_cache: yes

  # bug with apt module won't detect these packages so have to raw install them
- name: install docker
  raw: sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  args:
    executable: /bin/bash

- name: add docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    name: "{{ username }}"
    groups:
      - docker
    append: yes

- name: Install Docker Module for Python
  pip:
    name: docker

- name: make sure docker is started
  service:
    name: docker
    state: started
    enabled: yes

- name: run hello world
  docker_container:
    name: hello-world
    image: hello-world
