---
- name: install python and pip 3
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip

- name: switch to python3
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: switch to pip3
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3
